name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Install .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Install .NET WebAssembly Tools
        run: dotnet workload install wasm-tools

      # Publish the site
      - name: Publish
        run: dotnet publish AdventCalendar/AdventCalendar.csproj -p:GHPages=true -c:Release -o:public

      # Read files in content directory and create JSON
      - name: Generate JSON with file names and last committers
        run: |
          TARGET_DIR="content"
          OUTPUT_FILE="public/wwwroot/committers.json"
          echo "[]" > "$OUTPUT_FILE"
          
          # Read all .md files in content directory except those named 'template'
          for file in $(find "$TARGET_DIR" -type f -name '*.md' -not -name 'template*'); do
            filename=$(basename "$file" .${file##*.})
            last_committer=$(git log -1 --pretty=format:'%an' -- "$file")
            echo "Last committer for $file: $last_committer"
            
            # Append JSON object to array
            temp_json=$(jq -n --arg name "$filename" --arg committer "$last_committer" '{name: $name, committer: $committer}')
            jq ". += [\$temp]" --argjson temp "$temp_json" "$OUTPUT_FILE" > temp_output.json && mv temp_output.json "$OUTPUT_FILE"
          done

      # Deploy the site
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public/wwwroot
          force_orphan: true
